#!/bin/bash 
set -e
set -v


# http://superuser.com/questions/196848/how-do-i-create-an-administrator-user-on-ubuntu
# http://unix.stackexchange.com/questions/1416/redirecting-stdout-to-a-file-you-dont-have-write-permission-on
# This line assumes the user you created in the preseed directory is vagrant
echo "vagrant ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/init-users
sudo cat /etc/sudoers.d/init-users


# Installing vagrant keys
wget --no-check-certificate 'https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub'
sudo mkdir -p /home/vagrant/.ssh
sudo chown -R vagrant:vagrant /home/vagrant/.ssh
cat ./vagrant.pub >> /home/vagrant/.ssh/authorized_keys


# Making changes to host file.
sudo mkdir -p /data
#chown www-data:www-data /data
sudo chmod 777 /data
cd /data
rm -fr *
sudo wget https://raw.githubusercontent.com/illinoistech-itm/manand1/master/itmo553/Week-14/Data/host-files/hosts-ela2?token=AX6eCz9ReFmt6VV62rCmrz6qA4rvNxZfks5ZAXJuwA%3D%3D
cat hosts-ela2* >hosts.ela2
sudo mv /etc/hosts /etc/hosts.backup
sudo cp /data/hosts.ela2 /etc/hosts
sudo chown root:root /etc/hosts
sudo chmod 644 /etc/hosts
sudo chown vagrant:vagrant ~/.ssh/authorized_keys

#Installing Elasticsearch
sudo apt-get -y install default-jre
wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
sudo sh -c "echo deb http://packages.elastic.co/elasticsearch/2.x/debian stable main > /etc/apt/sources.list.d/elasticsearch.list"
sudo apt-get update
sudo apt-get -y install elasticsearch
sudo /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head

#Configuring and enabling cluster for elasticsearch
cd /etc/elasticsearch/
sudo mv elasticsearch.yml elasticsearch.yml_old
sudo wget https://raw.githubusercontent.com/illinoistech-itm/manand1/master/itmo553/Week-14/Data/elasticsearch-esa2.yml?token=AX6eC6uZyFJmooG4tNvpZXZBmIrU5ghvks5ZAXK4wA%3D%3D
sudo mv elasticsearch-esa2.yml* elasticsearch.yml

echo "All Done!"
